services:
  inkeep-agents-manage-api:
    build:
      context: .
      dockerfile: Dockerfile.manage-api
    ports:
      - "3002:3002"
    environment:
      - DB_FILE_NAME=file:/inkeep-agents/db/local.db
    volumes:
      - inkeep-agents-db:/inkeep-agents/db
  inkeep-agents-run-api:
    build:
      context: .
      dockerfile: Dockerfile.run-api
    ports:
      - "3003:3003"
    environment:
      - DB_FILE_NAME=file:/inkeep-agents/db/local.db
      - ANTHROPIC_API_KEY
    volumes:
      - inkeep-agents-db:/inkeep-agents/db

volumes:
  inkeep-agents-db:
