services:
  inkeep-agents-manage-ui:
    build:
      context: .
      dockerfile: Dockerfile.manage-ui
    environment:
      - ENVIRONMENT
      - LOG_LEVEL
      - INKEEP_AGENTS_MANAGE_API_URL=${INKEEP_AGENTS_MANAGE_API_URL:-http://inkeep-agents-manage-api:3002}
      - INKEEP_AGENTS_RUN_API_URL=${INKEEP_AGENTS_RUN_API_URL:-http://localhost:3003}
      - INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET
      - INKEEP_AGENTS_RUN_API_BYPASS_SECRET
      - NANGO_CONNECT_BASE_URL=${NANGO_CONNECT_BASE_URL:-http://localhost:3051}
      - NANGO_SERVER_URL=${NANGO_SERVER_URL:-http://localhost:3050}
      - NANGO_SECRET_KEY
      - SIGNOZ_URL=${SIGNOZ_URL:-http://localhost:3080}
      - SIGNOZ_API_KEY
    ports:
      - "3000:3000"
    depends_on:
      inkeep-agents-migrate:
        condition: service_completed_successfully
  inkeep-agents-manage-api:
    build:
      context: .
      dockerfile: Dockerfile.manage-api
    environment:
      - ENVIRONMENT
      - LOG_LEVEL
      - DB_FILE_NAME=file:/inkeep-agents/db/local.db
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN
      - INKEEP_AGENTS_MANAGE_API_BYPASS_SECRET
      - NANGO_SERVER_URL=${NANGO_SERVER_URL:-http://localhost:3050}
      - NANGO_SECRET_KEY
    volumes:
      - inkeep-agents-db:/inkeep-agents/db
    ports:
      - "3002:3002"
    depends_on:
      inkeep-agents-migrate:
        condition: service_completed_successfully
  inkeep-agents-run-api:
    build:
      context: .
      dockerfile: Dockerfile.run-api
    environment:
      - ENVIRONMENT
      - LOG_LEVEL
      - DB_FILE_NAME=file:/inkeep-agents/db/local.db
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN
      - INKEEP_AGENTS_RUN_API_BYPASS_SECRET
      - ANTHROPIC_API_KEY
      - OPENAI_API_KEY
      - GOOGLE_GENERATIVE_AI_API_KEY
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-http://localhost:14318/v1/traces}
      - OTEL_EXPORTER_OTLP_TRACES_HEADERS
      - NANGO_SERVER_URL=${NANGO_SERVER_URL:-http://localhost:3050}
      - NANGO_SECRET_KEY
    volumes:
      - inkeep-agents-db:/inkeep-agents/db
    ports:
      - "3003:3003"
    depends_on:
      inkeep-agents-migrate:
        condition: service_completed_successfully
  inkeep-agents-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - ENVIRONMENT
      - LOG_LEVEL
      - DB_FILE_NAME=file:/inkeep-agents/db/local.db
      - TURSO_DATABASE_URL
      - TURSO_AUTH_TOKEN
    volumes:
      - inkeep-agents-db:/inkeep-agents/db
    restart: "no"
volumes:
  inkeep-agents-db:
