FROM node:22-alpine

WORKDIR /inkeep-agents

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY turbo.json drizzle.config.ts ./

COPY scripts/ ./scripts/
COPY apps/shared/ ./apps/shared/

COPY apps/manage-api/ ./apps/manage-api/

RUN npm install -g pnpm@10.17.0

RUN pnpm install --frozen-lockfile

WORKDIR /inkeep-agents/apps/manage-api

EXPOSE 3002

CMD ["pnpm", "dev"]
